### ISSUE TITLE
Missing "formation" value causes invalid tag during Docker build

### ISSUE THREAD

**Issue by ChiefOfGxBxL** [jctaveras/heroku-deploy#21]
**Problem**: If the `formation` argument is not provided in the configuration, the Docker build fails with the following message: `invalid argument "registry.heroku.com/***" for "-t --tag" flag: invalid reference format`

**How to reproduce**:
Method 1: Use the latest version of this action, and leave the `formation` value blank
Method 2: Build any Docker image with a `--tag` that contains a trailing slash to confirm that Docker does not allow trailing slashes at the end of a tag (see below for details)

**What's appears to be causing the issue**  
The README indicates that for the `formation` value, the default value is `web`. However, the existing code does not have that default.
![image](https://user-images.githubusercontent.com/4079034/133351100-8b6c2aa2-a34b-414f-a463-0a82337dead9.png)

This means that on [index.js:26](https://github.com/jctaveras/heroku-deploy/blob/master/index.js#L26) the `--tag` parameter given to the Docker build command will have a trailing slash:
```js
await exec(`docker build --file ${dockerFilePath}/Dockerfile ${buildOptions} --tag registry.heroku.com/${appName}/${formation} ${dockerFilePath}`);
```

Tag: `--tag registry.heroku.com/${appName}/${formation}`
e.g. with `appName`="exampleApp" and `formation`="" --> `--tag registry.heroku.com/exampleApp/`

It looks like Docker build does not like the trailing slash in the tag. If I provide a `formation` value (even though the README says this value is optional) the build succeeds.

**Comment by jctaveras** [comment]
Formation is no longer supported, please read the ChangeLog on [version 3.0.0](https://github.com/jctaveras/heroku-deploy/releases/tag/v3.0.0) to see the new changes to the action
