### ISSUE TITLE
Heroku Push Missing Params

### ISSUE THREAD

**Issue by aminpaks** [jctaveras/heroku-deploy#23]
Hi there,

Thanks for building this Github Action, will you be open to improvements?
I noticed that the `heroku push` command is missing the extra parameters. As it builds the image and not the `docker build` the built image is missing the build args.

**Comment by jctaveras** [comment]
@aminpaks Using `heroku:push` simplifies a lot of the logic. You can check the changes on the new released version `v3.0.0` 🚀
