### ISSUE TITLE
Self hosted runner

### ISSUE THREAD

**Issue by meska** [jctaveras/heroku-deploy#4]
Hello,
Im trying your addon on a selfhosted runner: [hosting-your-own-runners](https://help.github.com/en/actions/hosting-your-own-runners).
I tested the configuration on official runner before and it works.

On selfhosted linux ubuntu 18.04.4 LTS I have this errror:
```
Authentication process faild. Error: Command failed: cat >~/.netrc <<EOF
    machine api.heroku.com
        login ***
        password ***
    EOF
/bin/sh: 1: cannot create ~/.netrc: Directory nonexistent
```

**Comment by jctaveras** [comment]
I see. I think it's time to improve the authentication process. I'll be working on this

**Comment by jctaveras** [comment]
@meska Please see the changes on #5 and update to the action to `v2.0.0`

**Comment by meska** [comment]
@jctaveras works, thank you
