### ISSUE TITLE
Cant run with named Dockerfile

### ISSUE THREAD

**Issue by mtsmachado8** [jctaveras/heroku-deploy#6]
Hello, thanks for the great action. A little issue tough.
Currently i cant run with 
options: '-f Dockerfile.something'
I tought that the problem was on `docker build --file Dockerfile . ${buildOptions} --tag registry.heroku.com/${appName}/web` because it already specify a filename. So i removed the `--file Dockerfile` part.

I found out that `heroku docker:push web -a ${app-name}` tries building the image again for some reason and dont use the image just built on docker build...

Iam currently trying with docker push registry.heroku.com/<app>/<process-type> as explained in https://devcenter.heroku.com/articles/container-registry-and-runtime#pushing-an-existing-image.

Any toughts to resolve that issue? i will let you know if i solve it.

**Comment by mtsmachado8** [comment]
Fixed with those two changes:
![image](https://user-images.githubusercontent.com/11022437/86833810-6add9c80-c070-11ea-90de-f2789033c60f.png)
PR opened... =)

**Comment by jctaveras** [comment]
@mtsmachado8 I saw your PR and I'm wondering: are you trying to push something different than a web app?

**Comment by mtsmachado8** [comment]
@jctaveras actually i am trying to push 2 webapps. My site and a storybook webapp with all components
So i need something like:
![image](https://user-images.githubusercontent.com/11022437/87973533-0e7e7200-ca9f-11ea-96a6-1a47c9020026.png)
That kind of flexibility would help when we have more than one project in the same repository (a monorepo approach).
In my case i have a ci/cd for each webapp. For those i use a different `-f Dockerfile.something`on options... It worked as i expected =)

**Comment by jctaveras** [comment]
@mtsmachado8 I suggest that you can just add the name of the image in this [line](https://github.com/jctaveras/heroku-deploy/pull/7/files#diff-168726dbe96b3ce427e7fedce31bb0bcR55). The function returns this value

```JavaScript
  return `${exportKey} heroku container:${action} web --app ${appName}`;
```

And I noticed in the [documentation](https://devcenter.heroku.com/articles/container-registry-and-runtime#pushing-an-existing-image) that you can add the name of the image that you want to push that means that you have to add a new input like `image_name` and the read that input in the [herokuAction](https://github.com/jctaveras/heroku-deploy/pull/7/files#diff-168726dbe96b3ce427e7fedce31bb0bcR51) function. The input can just be the ending part like `storybook` or the whole docker file name like `Dockerfile.storybook`

```yml
  input:
    image_name:
      default: web
      required: true
      description: Docker Image Name
```

```JavaScript
  const imageName = core.getInput('image_name');

  return `${exportKey} heroku container:${action} ${imageName} --app ${appName}`;
```

Or you will have to process the image name I case you decide to include the whole name

```yml
  input:
    image_name:
      default: Docker
      required: true
      description: Docker Image Name
```

```JavaScript
  const imageName = core.getInput('image_name');
  const image = imageName.match(/\.\w+$/g) || [];
  const tag = image[0].replace(/\./g, '') || 'web';

  return `${exportKey} heroku container:${action} ${tag} --app ${appName}`;
```

**Comment by jctaveras** [comment]
This should be addressed on the newest version of the action
