### ISSUE TITLE
How change dyno formation

### ISSUE THREAD

**Issue by caioreix** [jctaveras/heroku-deploy#9]
How can i change the dynos formation ?
![image](https://user-images.githubusercontent.com/62818416/96792905-b7f03f00-13d1-11eb-9f7b-be4c4e82c1f2.png)

**Comment by jctaveras** [comment]
By changing the formation [here](https://github.com/jctaveras/heroku-deploy/blob/master/index.js#L27). Right now is web but I can change it so the action can take `formation` as a variable set by the user.

**Comment by caioreix** [comment]
If possible, please. If the formation is web, and the application does not connect to the port will handle this error in heroku `Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch`

**Comment by jctaveras** [comment]
@caioreix you can read the [How to Use It](https://github.com/jctaveras/heroku-deploy#how-to-use-it) section in the README to see how to change the Heroku Dyno Formation. This should address this issue.
